const { assert } = require('chai');

describe("String doubles",() =>{

  function doubles(s){
    var replace = s.replace(/(.)\1/g, '');
    return s == replace ? s : doubles(replace);
  }
  
  // function doubles(s){
  //   var replaced = s;
  //   do {
  //     var original = replaced;
  //     replaced = original.replace(/(.)\1/g, '');
  //   } while(replaced != original);

  //   return replaced;
  // }

  it('Basic tests', () => {
    assert.strictEqual(doubles('abbbzz'),'ab');
    assert.strictEqual(doubles('zzzzykkkd'),'ykd');
    assert.strictEqual(doubles('abbcccdddda'),'aca');
    assert.strictEqual(doubles('vvvvvoiiiiin'),'voin');
    assert.strictEqual(doubles('rrrmooomqqqqj'),'rmomj');
    assert.strictEqual(doubles('xxbnnnnnyaaaaam'),'bnyam');
    assert.strictEqual(doubles('abba'),'');

    assert.strictEqual(
      doubles('ccuuldnvpztfuuoodpaaqqqqqqvvplbhiikkggzwwpqqyyjkkdyyrssdaassaassfeeyydtpyyggccnssccxmmiisseewwllnvzbvkkvhrjeemmfeeiizjggmmvpwwuuuuzaammyyggveejyykkpfsseessuuqqngglhjiizxuudaawwccvccxqqvtkkiisshmmxnoommxpqqiiwwdtpwwvbljggtliiyybaahuuccqqhbccaaqqwwzooeevuuaapkkoobsspooooiiggtnnyyqqsspxniiuuldootsskkiikkxbaaccvlprsshzoodnyytuufuuhtggaajaaqqhhcchyybnzxzbmmjvqqhkkssqqdmmiitssqqccvuummkkaapdssnkkbwwbjnyybaajsshhooggfqqoofqqaapmmgguuoonvzbbteexkkyydvrccvlqqmmtcciipssbzbqqdftjzxsseeeeggzaaflzfziibwwtwwbruuvwwggaassfdrrlneedhuuwwqqbkkdnteelwwmmcchjssggrzuuccnfdzhjpuujrtndhdltjvqqtuutookkggwwiijjhwwtiivdlpggaawwpuunlzztccuuooqqlfyyleeiiwwggeeaajvoonqqznbnpfzbjmmrzrxqqfdjiizwwbzggkkxccbwwtdxeewwqqpmmlaapggccwwiirqqpiiiinmmjooaaqqeeoodxeeyyuuaaaauuqqwwwwlpccoowwzooiissryyhuuooccfeejmmjaanaassfeefkknmmbyyaaooxvtzlggccjjqqaaggrqqaadzbccccbccxwwbdkkeeaayyggdbkktdccggwwvwwjyyaassiizssaaxzaallzyyssxiidmmptrznpqqlyyiipuupggaauukkyydriiccfffltrooteemmggfdprlbdyyiitqquujaanpccttzfqqccjxhbxmmuuuujuummooaauussssrdwwmmmmbzeeccssbftdjmmhuussccdeelggtflooaabwwbrbxfccccooblcckkmmgguupiidaauulqqrpiikkhdkkkkyyvzviibnaaccfrrggooccssprlyywwmmztggwwccsswwiixnxhvqqssddkkccrvhooqqrtccdiiccoojlvkkkkiihteenmmaaoolmmiiqqnqqjhpggssyyqqleehjmmqqnsstdggneeiiooeezjdkknooiidngglmmqqfggdccjggncciivdthssqqrhhaabuufnmmhuuxruuhuuxooqqkkbroouueevnggjcclcceekkssyyoooovpnccpiiiibssuuaatlwwpbaapooooaaiissfuuccfkkaarooiiqqjiiaauugglmmxiiaaeeoohmmssllccaammrbjccmmeelbyypwwvkkiivggzccwwjuufqqbjyyuuggpmmmmrnbddhzlooflsshaavcciijuuoohhkkooccdfrvlrxssggrvdkkdtlbssttveebxyyldoodooooooooqqkknkkeesssszmmaatplvjmmqqrdssaaiinfoohggqqrtplduurkkvjjmmccjyywwjmmxzwwoofblccdkkaadhooiiwwroocctggggeeoobvooxxfyyqqpzlggeeccssssruuyyvnmmkkpccqqbaaccootssbccfjbbdrpliijeehzlssaadpeekkhrwwwwtjllggvjssyykkiiggkkjbhqqvccqquuhzkkuupvhkkfiiqqvxiimmvliitiieeuuzccxggfeeiihyyhruutvjzrfccsseegguuggdeetbrrpkkoovwwjiihfzxaabnoovfdiiziicckklccxwwmmssssuummgghpaaxaajraazeeiifpkkmmuuaaggjrccaavxzyyzraavlhuuggssdduuxssfccccooxyyiiaayyfraaaantkkccxuuxwwuuxtkkeepqqhkklxwwssaatkkkkwwbxcclfyyprraatmmggpiivjpfzyyuuaaxwwoosszwwssxrxddqqaawwmmmmyywwqqccjaammrpbriizdrpccbvggtmmwwqqzzdxhvfyywwbiikksslsszfvvuupqqwwthdzdggjccccwwiirtuuiifwwfkkpkkxdvpxkkxpoowwjoonsstoovlnkkroodpteebiiyyndnvqqwwbjyyiioobuuhlhcciibbpiieeuuccyyaammccccuueemmggeejqqlmmzjoooommbggwwwwggbaauulfzfnqquuiidltcciiggiioofxxkkqqeepxeepmmkkthkkpplwwheeoosswwhiiyyfwweessqqcceejrbookkvhhraaoowwtiikkrbnbkkoovbwwbfmmuuzxxjnzbjpggpssaatoogghuueeggpeemmeelhtdjssjbznluuppmmuunfvvyyvjloozggssiivndxpccssyyxuuhtoogguunuunootdaankkdmmvqqdeelxjbiifccfwwyydssmmzaahdkkjzcciifdhxkkvmmeehljjdccyytggnpwwrduuiipsszjxkkkkztqqiibmmoohqqwwcceeuunbooqqwwkkqqmmfoofqqeeiiggpeehccxkkcckkmmpeessggwweemmhjwwxmmloowwqqgguukklldcctbhssltpqqggzphzqqiizjnuuzuuaaiilnnoojzqqhggmmggdkkqqtznqqlptkktphyyhjloobnreedpxzhbaapeeeepbnkkwwggjduussccbwwwwccmmvcckkhaauuyyaauuqqxkkdccvjdxnggmmfqqrxoowwtqquummxeevqqntiixxhtwwuummaadfluutssjjlbzlvtcczdpyyfxjjeettlssgglxhlqqnoozbwwyyaafvccssveewwdneefuuuuxhxhzrggiiuunyybdyybwwiieeoobfbaaprjfzkkeendeesswwuudkkrlheeggdssbmmplmmflaakkrjoofrvrmmoorzjyyhrvptrlaaqqssaarkkvyyntnjrqqwwqqcceerdgguuzwwuurpaassccqqxjeekkbjuummoogglkkhwweexwwwwvrxfjuuzbccoovuupbvldzuuqqzznuupeekkqqfqqeekkcclrssqqxbvpnzxbggbpiirggccyyzqqkklhkkootqqqqrqqdtnkkccvccdwwjjpkkuutvaaggreebqqaaqqfhyytyywwiiuuxwwnssyyxmmbhdnqqyylaafaassluufwwcciihoohaassxnflziiuupssfzggeeqqqqiiiiaammzcchyyssrjxkkggvooaaqquurwwluuooiimmwwqqyyraassggqqeekkhkkzlcceehyyxeeooreekkiiwwxtqqggtwwprsseejbaajyyeeriioogghjvnnwwbcccceehggssyyjroouuoopriihssbzzsseeiiuuvqqyydqqtkklkkiizhtnzeeccssrqqxyyaaggeejzmmccoojzhuuvssjhuulaatpvwwjvxccccfkkhsshqqzaanrbkkbtsstmmjhmmsskkggggtlnaakkxrwwlyyruutmmccooeeloohyylssmmmmxsscchzjhwwmmnuudwwriikkkkrssvqqqqggssdeerooeeyybviivhdtbiivjuuyypvlggnzzzfqqccdsshrmmqqaaxpdtggssssxmmtccbdggnjbdrjeemmjwwwwkkyymmpfzjxggjaalqqssptootmmtjdssdkkxzjlcceemmeermmzjoouuxlxggdwwmmcchqqbqqxeeqqfbwwiissdkkyylvduugghooeehmmjpmmxuuwwlzcceeaajlqqrqqmmnkkeernmmrdpjwweeccryymmoowwmmhhyymmhrvhaalooeeqqnxnssteeliidnccnfkkeeuuwwhhtiixjveefxdwwxwwzbccwwfoowwuuxiiwwkkfiibpleefssnfblggiivhuuoofhlvqqyyggrfaacclkkhyyyyggggdxqqwwbiijoorfnsshzccsseessccookkqqaassxuuraajssccjduuccsspaaggdbzaaxfmmssaaoohkkooyy'),
      'ldnvpztfdlbhzpjdrdfdtpnxnvzbhrjfzjvpzvjpfnlhjzxdvxvthxnxpdtpvbljtlzvpbptpxnldtxbvlprhzdntfhtjhbnzxzbjvhdtvpdnjnbjpnvztxdvrvltpbzbdftjzxzflzfzbtbrvfdlndhbdntlhjrznfdzhjpjrtndhdltjvhtvdlnltlfljvnznbnpfzbjrzrxfdjzbzxbtdxplprpnjdxlpzrhfbxvtzlrdzxtdvjzdptrznpldrfltrtfdprlbdtjnpzfjxhbxjrdbzbftdjhdltflrbxfblpdlrphdvzvbnfprlztxnxhvrvhrtdjlvhtnlnjhplhjntdnzjdndnlfdjnvdthrbfnhxrhxbrvnjlvpnpbtlpbprjlxhrbjlbpzjfbjprnbhzlflhvjdfrvlrxrvtlbvbxlnztplvjrdnfhrtpldrvxzfblhrtbvfpzlrvnpbtbfjdrpljhzldphrtjvbhvhzpvhfvxvltzxfrtvjzrfdtbpvjhfzxbnvfdzlxhpxjrzfpjrvxrvlhxfxfrntxtphlxtbxlfptpvjpfzxzxrxjrpbrzdrpbvtdxhvfblzfpthdzdjrtpxdvjntvlnrdptbndnvbjbhlhpjlzjlfzfndltfpxpthlfjrbvrtrbnbvfzjnzbjthplhtdbznlnfvjlzvndxpxhdndvdlxjbdzhdjzfdhxvhldtnprdpzjxztbhnbphxphjxldtbhltpzphjnzljzhdtznljlbnrdpxzhnjdbvhxdvjdxnfrxtxvnthtdfltlbzlvtzdpfhlnzbfdnfxhxhzrnbdfbprjfznrlhdbplflrjfrvzjhrvptrlrvntnjdzrpxjbjlhxvrxfjzbvpbvldznpflrxbvpnzxprzlhtrdtnvdptvrbfhtxnxbhdnlflfxnflzpfhrjxvrlrhzlhxrxprjbjrhjvbhjrprhbvdtlzhtnzrxjzjzhvjhltpvjvxfznrjhtlnxrlrtlhlxhzjhndvdrbhdtbvjpvlnzfdhrxpdtxtbdnjbdrpfzjxjlptjxzjlrzjxlxdhbxfbdlvdjpxlzjlrnrnrdpjrhrvhlnxntldftxjvfxdxzbfxfbplfnfblvhfhlvrflhdxbjrfnhzxrdpdbzxfh');
  })

})

